apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJSR1Z1TVRFeE1qSXlPbWRvY0Y5M2VVMXZXbWt6YWxKUWJ6RkhRbmxtYzJkMU5XeEdabEJWUkdZd1EzZ3pibE55T0VZPSJ9fX0=
type: kubernetes.io/dockerconfigjson
